//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_account")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub email: Option<String>,
    pub username: Option<String>,
    pub hashed_password: Option<String>,
    pub password_salt: Option<String>,
    pub password_hash_algorithm: Option<String>,
    pub role_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_role::Entity",
        from = "Column::RoleId",
        to = "super::user_role::Column::RoleId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserRole,
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
